# Generated by Django 5.2.12 on 2026-04-25 19:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('command', models.CharField(help_text='Django management command (e.g., notify_due_tasks).', max_length=120)),
                ('cron_expression', models.CharField(blank=True, help_text='Display-only schedule (e.g., "0 9 * * *"). The cron itself runs externally.', max_length=64)),
                ('owner_product', models.CharField(db_index=True, help_text="Which product declared this job — 'helm', 'admiralty', etc.", max_length=32)),
                ('description', models.TextField(blank=True)),
                ('timeout_minutes', models.PositiveIntegerField(blank=True, help_text='If a run exceeds this, the dashboard flags it as overdue.', null=True)),
                ('enabled', models.BooleanField(default=True, help_text='Display flag — does NOT actually pause the cron. Manage that in Railway / your scheduler. Use this to mark jobs as expected-disabled so the dashboard does not flag missing runs.')),
                ('notes', models.TextField(blank=True, help_text='Admin notes — runbook URL, escalation path, etc.')),
                ('declared_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['owner_product', 'slug'],
                'indexes': [models.Index(fields=['owner_product', 'enabled'], name='keel_schedu_owner_p_81cfaa_idx')],
            },
        ),
        migrations.CreateModel(
            name='CommandRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('error', 'Error'), ('skipped', 'Skipped')], db_index=True, default='running', max_length=16)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('invoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='keel_scheduling.scheduledjob')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['job', '-started_at'], name='keel_schedu_job_id_eb5f95_idx'), models.Index(fields=['status', '-started_at'], name='keel_schedu_status_ac1b61_idx')],
            },
        ),
    ]
