# Generated by Django 6.0.3 on 2026-03-20 14:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submitted_by_name', models.CharField(blank=True, help_text='Captured at submission time in case user is deleted.', max_length=255)),
                ('submitted_by_email', models.EmailField(blank=True, max_length=254)),
                ('product', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(help_text='Describe what you want changed, added, or fixed.')),
                ('category', models.CharField(choices=[('bug', 'Bug Report'), ('feature', 'Feature Request'), ('ui', 'UI/UX Improvement'), ('data', 'Data/Report Request'), ('workflow', 'Workflow Change'), ('other', 'Other')], default='feature', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('page_url', models.CharField(blank=True, help_text='The page this relates to (if applicable).', max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('declined', 'Declined'), ('implementing', 'Implementing'), ('implemented', 'Implemented')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Scope, constraints, or implementation guidance.')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('decline_reason', models.TextField(blank=True)),
                ('implemented_at', models.DateTimeField(blank=True, null=True)),
                ('implementation_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'change request',
                'verbose_name_plural': 'change requests',
                'db_table': 'keel_change_request',
                'ordering': ['-created_at'],
            },
        ),
    ]
