# Generated by Django 5.2.13 on 2026-05-14 13:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MentionDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note_object_id', models.UUIDField()),
                ('recipient_kind', models.CharField(choices=[('keel_user', 'KeelUser'), ('beacon_contact', 'Beacon contact')], max_length=24)),
                ('recipient_ref', models.CharField(blank=True, max_length=128)),
                ('recipient_peer_url', models.URLField(blank=True)),
                ('delivered_at', models.DateTimeField(auto_now_add=True)),
                ('peer_status', models.CharField(blank=True, choices=[('', ''), ('ok', 'OK'), ('failed', 'Failed'), ('gone', 'Gone')], default='', max_length=16)),
                ('peer_error', models.TextField(blank=True)),
                ('note_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'mention delivery',
                'verbose_name_plural': 'mention deliveries',
                'indexes': [models.Index(fields=['recipient_user', '-delivered_at'], name='keel_mentio_recipie_a4a65e_idx'), models.Index(fields=['recipient_kind', 'recipient_ref'], name='keel_mentio_recipie_d8ee80_idx'), models.Index(fields=['note_content_type', 'note_object_id'], name='keel_mentio_note_co_5bf2cf_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('recipient_kind', 'keel_user')), fields=('note_content_type', 'note_object_id', 'recipient_user'), name='unique_mention_delivery_user'), models.UniqueConstraint(condition=models.Q(('recipient_kind', 'beacon_contact')), fields=('note_content_type', 'note_object_id', 'recipient_ref'), name='unique_mention_delivery_contact'), models.CheckConstraint(condition=models.Q(models.Q(('recipient_kind', 'keel_user'), ('recipient_ref', ''), ('recipient_user__isnull', False)), models.Q(('recipient_kind', 'beacon_contact'), ('recipient_user__isnull', True)), _connector='OR'), name='mention_delivery_shape_consistent')],
            },
        ),
    ]
