# Generated by Django 5.2.12 on 2026-04-21 13:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManifestHandoff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_app_label', models.CharField(max_length=64)),
                ('source_model', models.CharField(max_length=64)),
                ('source_pk', models.CharField(max_length=64)),
                ('attachment_model', models.CharField(max_length=128)),
                ('attachment_fk_name', models.CharField(max_length=64)),
                ('on_approved_status', models.CharField(max_length=64)),
                ('manifest_packet_uuid', models.CharField(blank=True, max_length=64)),
                ('manifest_url', models.URLField(blank=True)),
                ('packet_label', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending — not yet sent to Manifest'), ('sent', 'Sent to Manifest; awaiting signatures'), ('signed', 'Completed; signed PDF returned'), ('failed', 'Send to Manifest failed'), ('local_signed', 'Locally signed (Manifest unavailable)'), ('cancelled', 'Cancelled before completion')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('signed_pdf_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manifest_handoffs_initiated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Manifest Handoff',
                'verbose_name_plural': 'Manifest Handoffs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source_app_label', 'source_model', 'source_pk'], name='kls_handoff_source_idx'), models.Index(fields=['manifest_packet_uuid'], name='kls_handoff_packet_idx')],
            },
        ),
    ]
