# Generated by Django 5.2.12 on 2026-04-03 19:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeadLetter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_payload', models.JSONField(help_text='Full Postmark webhook body.')),
                ('from_address', models.EmailField(max_length=254)),
                ('to_address', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('reason', models.CharField(choices=[('unroutable', 'Address did not match expected format'), ('no_mailbox', 'No active mailbox for this address'), ('parse_error', 'Failed to parse webhook payload'), ('wrong_domain', 'Address domain does not match tenant')], max_length=20)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MailboxAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('product', models.CharField(help_text='Product slug: harbor, admiralty, beacon, bounty, etc.', max_length=50)),
                ('entity_id', models.UUIDField()),
                ('display_name', models.CharField(help_text='Friendly sender name, e.g. "Harbor – Grant #4821".', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'mailbox address',
                'verbose_name_plural': 'mailbox addresses',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=8)),
                ('from_address', models.EmailField(max_length=254)),
                ('from_name', models.CharField(blank=True, max_length=255)),
                ('to_addresses', models.JSONField(default=list)),
                ('cc_addresses', models.JSONField(default=list)),
                ('reply_to', models.EmailField(blank=True, max_length=254)),
                ('subject', models.CharField(max_length=500)),
                ('body_text', models.TextField(blank=True)),
                ('body_html', models.TextField(blank=True)),
                ('message_id_header', models.CharField(db_index=True, help_text='RFC 5322 Message-ID header value.', max_length=995, unique=True)),
                ('in_reply_to_header', models.CharField(blank=True, db_index=True, help_text='RFC 5322 In-Reply-To header value.', max_length=995)),
                ('references_header', models.JSONField(default=list, help_text='RFC 5322 References header values (list of Message-IDs).')),
                ('sent_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('postmark_message_id', models.CharField(blank=True, max_length=255)),
                ('delivery_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('bounced', 'Bounced'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('delivery_detail', models.JSONField(blank=True, default=dict, help_text='Bounce info, error details, etc.')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sent_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size_bytes', models.PositiveIntegerField()),
                ('file', models.FileField(upload_to='comms/attachments/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='keel_comms.message')),
            ],
            options={
                'ordering': ['filename'],
            },
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=500)),
                ('is_archived', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mailbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='keel_comms.mailboxaddress')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='message',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='keel_comms.thread'),
        ),
        migrations.AddIndex(
            model_name='mailboxaddress',
            index=models.Index(fields=['entity_type', 'entity_id'], name='keel_comms__entity__d616c0_idx'),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['mailbox', '-updated_at'], name='keel_comms__mailbox_01a07a_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['thread', 'sent_at'], name='keel_comms__thread__babee1_idx'),
        ),
    ]
