# Generated by Django 5.2.12 on 2026-04-03 20:13

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keel_comms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
    ]
