"""Django system checks for keel.mentions.

Three checks fire on ``manage.py check`` and at boot:

    keel.mentions.W001 — keel.mentions installed but URL include missing
    keel.mentions.W002 — MentionFormMixin subclass missing the widget
    keel.mentions.W003 — concrete AbstractInternalNote subclass missing
                          its mentions M2M migration

These exist because every failure mode they catch is otherwise a silent
no-op at runtime. They make misconfiguration loud at boot.
"""
from __future__ import annotations

from django.apps import apps
from django.conf import settings
from django.core.checks import Warning as DjangoWarning
from django.core.checks import register


@register()
def check_urls_included(app_configs, **kwargs):
    """W001: keel.mentions is in INSTALLED_APPS but URL include missing.

    Catches NoReverseMatch only — broader exceptions (ImproperlyConfigured
    during partial urlconf load, e.g. mid-makemigrations) are skipped
    silently so this check doesn't spam warnings during management
    commands that don't fully load the URL graph.
    """
    if 'keel.mentions' not in settings.INSTALLED_APPS:
        return []
    try:
        from django.urls import NoReverseMatch, reverse
    except ImportError:
        return []
    try:
        reverse('keel_mentions:mentions_search')
        return []
    except NoReverseMatch:
        return [
            DjangoWarning(
                "keel.mentions is installed but its URLs are not included.",
                hint=(
                    "Add path('keel/mentions/', include('keel.mentions.urls')) "
                    "to your product's root urls.py."
                ),
                id='keel.mentions.W001',
            ),
        ]
    except Exception:
        # Urlconf not fully loaded (likely a management command mid-boot).
        # Skip silently — the check will run again on a real request.
        return []


@register()
def check_mention_form_widgets(app_configs, **kwargs):
    """W002: any MentionFormMixin subclass whose 'content' widget is wrong.

    Only fires when the form has been defined at app-config time and the
    widget on ``content`` is not a MentionableTextarea. This is best-effort
    (we can't know every form class at boot), but it catches the common
    case where the mixin is wired in but the widget swap was forgotten.
    """
    from django.forms import Field

    from .forms import MentionFormMixin
    from .widgets import MentionableTextarea

    warnings: list[DjangoWarning] = []
    seen: set[str] = set()
    for subclass in MentionFormMixin.__subclasses__():
        # Walk the MRO so subclass chains are also checked.
        for klass in [subclass, *subclass.__subclasses__()]:
            if not hasattr(klass, 'base_fields'):
                continue  # not a ModelForm-like class
            cls_name = f'{klass.__module__}.{klass.__qualname__}'
            if cls_name in seen:
                continue
            seen.add(cls_name)
            content_field: Field | None = klass.base_fields.get('content')
            if content_field is None:
                continue
            widget = content_field.widget
            if not isinstance(widget, MentionableTextarea):
                warnings.append(DjangoWarning(
                    f"{cls_name} uses MentionFormMixin but the 'content' "
                    f"widget is {type(widget).__name__}, not MentionableTextarea.",
                    hint=(
                        "Set `widgets = {'content': MentionableTextarea()}` "
                        "on the form's Meta, or assign the widget in __init__."
                    ),
                    id='keel.mentions.W002',
                ))
    return warnings


@register()
def check_mentions_migrations(app_configs, **kwargs):
    """W003: concrete AbstractInternalNote subclasses missing the M2M.

    Walks the app registry; for every concrete model that inherits
    ``AbstractInternalNote``, asserts the local table has a ``mentions``
    M2M field. The migration generated by ``makemigrations`` after
    bumping keel to 0.42.0 is what populates this.
    """
    if 'keel.mentions' not in settings.INSTALLED_APPS:
        return []

    from keel.core.models import AbstractInternalNote

    warnings: list[DjangoWarning] = []
    for model in apps.get_models():
        if not issubclass(model, AbstractInternalNote):
            continue
        if model._meta.abstract:
            continue
        try:
            model._meta.get_field('mentions')
        except Exception:
            warnings.append(DjangoWarning(
                f"{model._meta.label} inherits AbstractInternalNote but is "
                "missing the 'mentions' M2M. The inherited field was added in "
                "keel 0.42.0 — run `python manage.py makemigrations "
                f"{model._meta.app_label}` and `migrate`.",
                hint='Lockstep rollout: the keel pin and per-product migration '
                     'must land in the same PR.',
                id='keel.mentions.W003',
            ))
    return warnings
