# Generated by Django 6.0.3 on 2026-03-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keel_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productaccess',
            name='is_beta_tester',
            field=models.BooleanField(default=False, help_text='Beta testers can submit feedback directly from within the product.'),
        ),
    ]
