# Generated by Django 5.2.12 on 2026-03-25 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keel_accounts', '0004_add_notification_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTypeOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, help_text='Notification type key (e.g., application_submitted).', max_length=100, unique=True)),
                ('channels', models.JSONField(blank=True, default=list, help_text='Override default_channels (e.g., ["in_app", "email"]).')),
                ('roles', models.JSONField(blank=True, default=list, help_text='Override default_roles (e.g., ["admin", "program_officer"]).')),
                ('priority', models.CharField(blank=True, help_text='Override priority (low, medium, high, urgent).', max_length=10)),
                ('allow_mute', models.BooleanField(help_text='Override allow_mute. Null means use hardcoded default.', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notification type override',
                'verbose_name_plural': 'notification type overrides',
                'db_table': 'keel_notification_type_override',
            },
        ),
    ]
