# Generated by Django 5.2.12 on 2026-03-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keel_accounts', '0005_add_notification_type_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='is_beta_tester',
            field=models.BooleanField(default=False, help_text='Grant beta tester status when invitation is accepted.'),
        ),
    ]
