# Generated by Django 5.2.12 on 2026-05-02 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keel_accounts', '0011_seed_default_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationproductsubscription',
            name='product',
            field=models.CharField(choices=[('beacon', 'Beacon CRM'), ('admiralty', 'Admiralty FOIA'), ('harbor', 'Harbor Grants'), ('manifest', 'Manifest Signing'), ('lookout', 'Lookout Legislative'), ('bounty', 'Bounty Federal Grants'), ('purser', 'Purser Finance'), ('helm', 'Helm Executive Dashboard'), ('yeoman', 'Yeoman Scheduling'), ('keel', 'Keel Admin')], help_text='Product code (e.g. harbor, beacon).', max_length=50),
        ),
        migrations.AlterField(
            model_name='productaccess',
            name='product',
            field=models.CharField(choices=[('beacon', 'Beacon CRM'), ('admiralty', 'Admiralty FOIA'), ('harbor', 'Harbor Grants'), ('manifest', 'Manifest Signing'), ('lookout', 'Lookout Legislative'), ('bounty', 'Bounty Federal Grants'), ('purser', 'Purser Finance'), ('helm', 'Helm Executive Dashboard'), ('yeoman', 'Yeoman Scheduling'), ('keel', 'Keel Admin')], max_length=50),
        ),
    ]
