# Generated by Django 5.2.12 on 2026-05-04 02:16

import keel.accounts.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keel_accounts', '0014_keeluser_timezone_locale'),
    ]

    operations = [
        migrations.AddField(
            model_name='keeluser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=keel.accounts.storage.avatar_storage, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='keeluser',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
