# Generated by Django 5.2.12 on 2026-05-04 14:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keel_accounts', '0015_keeluser_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingEmailChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('new_email', models.EmailField(max_length=254)),
                ('token', models.CharField(db_index=True, max_length=128, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_email_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'pending email change',
                'verbose_name_plural': 'pending email changes',
                'db_table': 'keel_pending_email_change',
                'ordering': ['-created_at'],
            },
        ),
    ]
