# Generated by Django 5.2.12 on 2026-05-04 17:42

import keel.accounts.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keel_accounts', '0016_pendingemailchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keeluser',
            name='avatar',
            field=models.ImageField(blank=True, max_length=200, null=True, storage=keel.accounts.storage.avatar_storage, upload_to='avatars/'),
        ),
    ]
