# Generated by Django 5.2.12 on 2026-05-07 22:49

import keel.security.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keel_accounts', '0017_keeluser_avatar_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='ai_enabled',
            field=models.BooleanField(default=True, help_text='Whether to grant AI access on this product when the invitation is accepted.'),
        ),
        migrations.AddField(
            model_name='keeluser',
            name='anthropic_api_key_encrypted',
            field=keel.security.fields.EncryptedTextField(blank=True, default='', help_text="User's Anthropic API key. Encrypted at rest. Set via Settings → AI; never edit directly in admin."),
        ),
        migrations.AddField(
            model_name='organizationproductsubscription',
            name='ai_enabled',
            field=models.BooleanField(default=False, help_text='Whether AI features are enabled for this org on this product. AI surfaces are gated by both this flag and the per-user ProductAccess.ai_enabled flag.'),
        ),
        migrations.AddField(
            model_name='productaccess',
            name='ai_enabled',
            field=models.BooleanField(default=True, help_text='Whether this user sees AI features in this product. Combined with OrganizationProductSubscription.ai_enabled and the user having an Anthropic API key configured.'),
        ),
    ]
