# Generated by Django 5.2.12 on 2026-05-05 21:43
#
# Hand-edited after generation: switched to ``atomic = False`` and a
# vendor-aware ``CREATE INDEX CONCURRENTLY`` (Postgres) / regular
# ``CREATE INDEX`` (SQLite fallback for the test runner). The default
# Django AddIndex emits a plain ``CREATE INDEX`` inside a transaction,
# which on a multi-million-row keel_user table would block writes for
# the duration of the index build — that's a several-minute outage on
# every Railway deploy. CONCURRENTLY runs without the exclusive lock;
# the trade-off is a longer wall-clock time and inability to run
# inside a wrapping transaction (hence ``atomic = False``).
#
# ``state_operations`` keeps Django's migration state in sync (so
# ``makemigrations`` doesn't try to re-add the index later) while
# ``database_operations`` runs the vendor-specific DDL.
import django.db.models.functions.text
from django.db import migrations, models


def _create_index_lower_email(apps, schema_editor):
    """Functional index on Lower(email) — CONCURRENTLY on Postgres."""
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute(
            'CREATE INDEX CONCURRENTLY IF NOT EXISTS '
            '"keeluser_email_lower_idx" ON "keel_user" (LOWER("email"))'
        )
    else:
        # SQLite (test runner fallback). Plain CREATE INDEX is fine —
        # test DBs are small and there are no concurrent writers.
        schema_editor.execute(
            'CREATE INDEX IF NOT EXISTS '
            '"keeluser_email_lower_idx" ON "keel_user" (LOWER("email"))'
        )


def _drop_index_lower_email(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute(
            'DROP INDEX CONCURRENTLY IF EXISTS "keeluser_email_lower_idx"'
        )
    else:
        schema_editor.execute(
            'DROP INDEX IF EXISTS "keeluser_email_lower_idx"'
        )


class Migration(migrations.Migration):

    atomic = False  # required for CREATE INDEX CONCURRENTLY on Postgres

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('keel_accounts', '0020_seed_existing_subs_ai_enabled'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    _create_index_lower_email,
                    _drop_index_lower_email,
                ),
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name='keeluser',
                    index=models.Index(
                        django.db.models.functions.text.Lower('email'),
                        name='keeluser_email_lower_idx',
                    ),
                ),
            ],
        ),
    ]
