# Generated by Django 5.2.16 on 2026-07-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keel_accounts', '0022_auditlog_user_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='email_cc',
            field=models.EmailField(blank=True, default='', help_text="Address CC'd on the invitation email, if any.", max_length=254),
        ),
        migrations.AddField(
            model_name='invitation',
            name='email_error',
            field=models.TextField(blank=True, default='', help_text='Mail-backend error from the last send attempt, if it failed. Empty on success.'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the invitation email was accepted by the mail backend. Null = never sent (or send failed).', null=True),
        ),
    ]
